# Generated by Django 5.2.3 on 2025-06-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('prazo', models.DateTimeField()),
                ('concluida_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
