# Generated by Django 5.2.3 on 2025-06-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefa",
            name="concluida_em",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="descricao",
            field=models.TextField(null=True),
        ),
    ]
