# Generated by Django 5.2.3 on 2025-06-30 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0002_alter_tarefa_concluida_em_alter_tarefa_descricao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tarefa",
            name="descricao",
        ),
    ]
