# Generated by Django 5.2.3 on 2025-06-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0003_remove_tarefa_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefa",
            name="concluida_em",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="prazo",
            field=models.DateField(),
        ),
    ]
